--- #YAML:1.0
name:                XML-SAX-Expat
version:             0.40
abstract:            SAX Driver for Expat
license:             perl
author:              
    - Robin Berjon
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    XML::NamespaceSupport:         0.03
    XML::Parser:                   2.27
    XML::SAX:                      0.03
    XML::SAX::Base:                1.00
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
