#!/bin/sh

if [ ! -f /etc/cernvm/tools.d/virtualbox ]; then
  exit 0
fi

if [ -f /etc/cernvm/site.conf ]; then
  . /etc/cernvm/site.conf
  if [ "x$CERNVM_USER" != "x" ]; then
    uid=$(id -u $CERNVM_USER)
    gid=$(id -u $CERNVM_USER)
    sflist=$(VBoxControl sharedfolder list | grep '^[0-9][0-9]* - ' | awk '{print $3}' | tr '\n' ' ')
    for folder in $sflist; do
      cat /proc/mounts | awk '{print $2}' | grep -q "^/mnt/shared/${folder}$" && continue
      mkdir -p /mnt/shared/${folder}
      chown ${CERNVM_USER}:${CERNVM_USER} /mnt/shared/${folder} > /dev/null 2>&1
      mount -t vboxsf -o uid=$uid,gid=$gid ${folder} /mnt/shared/${folder} > /dev/null 2>&1 || true
    done
  fi
fi

exec /usr/sbin/VBoxService

